<?php

namespace app\api\controller;

use app\api\model\UserModel;

class User extends CommonController
{
    private $model;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new UserModel();
    }

    function register()
    {
        $userName = $this->params['user_name'];
        $res = db('user')->where('user_name', $userName)->find();
        if ($res) {
            responseError('用户名重复');
        }
        $userPwd = $this->params['user_pwd'];
        $res = db('user')->insert([
            'user_name' => $userName,
            'user_pwd' => $userPwd,
            'create_time' => time(),
            'update_time' => time()
        ]);
        if ($res !== false) {
            $user = db('user')->where('user_name', $userName)->find();
            responseData($user);
        }
    }

    function getCode()
    {
        responseData(['code' => $this->model->generateCode(4)]);
    }

    function login()
    {
        $type = $this->params['login_type'];
        $userName = $this->params['user_name'];
        if ($type == 0) {
            $pwd = $this->params['user_pwd'];
            $res = db('user')->where('user_name', $userName)->find();
            if (!$res) {
                responseError('用户不存在');
            }
            if ($pwd != $res['user_pwd']) {
                responseError('用户名或密码错误');
            }
            unset($res['user_pwd']);
            responseData($res);
        } else if ($type == 1) {
            $code = $this->params['code'];
            $res = db('user')->where('user_name', $userName)->find();
            if (!$res) {
                responseError('用户不存在');
            }
            unset($res['user_pwd']);
            responseData($res);
        } else {
            responseError('登录类型无效');
        }
    }

    /**
     * 更新密码
     */
    function updatePassword()
    {
        $userName = $this->params['user_name'];
        $newPwd = $this->params['new_pwd'];
        $res = db('user')->where('user_name', $userName)->find();
        if (!$res) {
            responseError('用户不存在');
        }

        if (isset($this->params['old_pwd'])) {
            //修改密码
            $oldPwd = $this->params['old_pwd'];
            if ($oldPwd !== $res['user_pwd']) {
                responseError('原密码错误');
            }
            $res = db('user')->where('user_name', $userName)->update([
                'user_pwd' => $newPwd
            ]);

            if ($res !== false) {
                responseData([], '修改成功');
            } else {
                responseError('修改失败');
            }

        } else {
            //忘记密码
            $code = $this->params['code'];
            if ($newPwd == $res['user_pwd']) {
                responseError('新密码与旧密码重复');
            }
            $res = db('user')->where('user_name', $userName)->update(['user_pwd' => $newPwd]);
            if ($res !== false) {
                responseData([], '修改成功');
            } else {
                responseError('修改失败');
            }
        }
    }
}
